spring.application.name=processor-service

server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbit.queue=events.raw

app.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5433/payments_db
app.datasource.postgres.username=postgres
app.datasource.postgres.password=postgres
app.datasource.postgres.driver-class-name=org.postgresql.Driver

app.datasource.clickhouse.jdbc-url=jdbc:clickhouse://localhost:8123/default?compress=0
app.datasource.clickhouse.username=app
app.datasource.clickhouse.password=app
app.datasource.clickhouse.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
